### PR TITLE
Added afternode, to conform to new React API.

### PR DESCRIPTION
**Pull request by jimfb**
Internal API changed in https://github.com/facebook/react/pull/5782

### CODE REVIEW

**Comment by jimfb** [comment]
@spicyj @sebmarkbage This requires the new React with https://github.com/facebook/react/pull/5782, but I'm not familiar with how the react dependency is managed in this repository.  Help?

**Comment by spicyj** [comment]
Can you get rid of the _mostRecentlyPlacedChild logic? It is basically recreating what I added. I think you just need to add getNativeNode to NodeMixin returning this.node and then `afterNode` should be just what you need. See #79 for how @zpao set up a dep on React master from react.zpao.com.

**Comment by zpao** [comment]
I just merged #79 so rebase and you'll be ok. It'll fail on travis (because `npm install` will "fail") but it should be fine locally.

**Comment by spicyj** [comment]
This is fine to merge as-is; we can do my change later.

**Comment by jimfb** [comment]
Ok, since zpao's npm depedency merged, master is broken atm.  I'm going to merge this to unblock (and also so we are consistent with the sync).  I'll try to take a look at the change you suggested later, ping me if I forget.

**Pull request merged**
