### PR TITLE
Add gulp-styled shell script to build and publish examples website

### LINKED ISSUE #39: Publish examples to Github pages
For us window shoppers :-)

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes #39 

Running `gulp build-examples-website` produced http://kyleamathews.github.io/react-art/vector-widget/

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I should mention this task assumes you've already run `npm install` in both the examples + base directories and that a `gh-pages` branch exists and has been pushed to origin.

**Comment by zpao** [comment]
:thumbsup: I think I'll tweak this a bit myself before merging (so you don't have to spend the time for something you aren't super committed to), but thanks for getting this started. It's super helpful!

(mostly, I don't like merging master into gh-pages, so I'll probably do what we did for other projects and just expect a react-art-gh-pages directory at the same level as the react-art checkout)

**Comment by zpao** [comment]
(also, gulp-shell gives me other ideas... might be time to look at replacing grunt in some other projects...)

**Comment by KyleAMathews** [comment]
:+1:

**Comment by sebmarkbage** [comment]
ping @zpao

**Pull request merged**
